### PR TITLE
Added the storeconfig master and slave

### PR DESCRIPTION
**Pull request by david-caro**
As we discussed before, I've separated the two master/slave options in storeconfigs and swarmplugin.

Also the sshkey that was needed before now is autogenerated and it's not needed anymore :)

Updated the docs too.

### CODE REVIEW

**Comment by david-caro** [comment]
Oops, it seems some libraries are missing:
Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

```
    /scratch/jenkins/rubies/ruby-1.8.7-p357-i686/bin/ruby extconf.rb 
```

## checking for libxml/parser.h... no

libxml2 is missing.  please visit http://nokogiri.org/tutorials/installing_nokogiri.html for help with installing dependencies.

I'm not sure if it's caused by my code, @rtyler can you take a look please?
Thanks!

**Comment by matthewbarr** [comment]
Only issue is that the lib/puppet/ code is pushed to the slaves no matter what :(

It becomes active the moment it's installed in the module path on the master.  Don't think there's a way to not use it.

**Comment by david-caro** [comment]
Afaik, there's no way to avoid it synchronizing. But it will not break
anything anyway. The only drawback it's maybe a little wait when reading
the facts. We could create a file to disable the facts from running any
more code, bit I don't think that it's worth adding the extra complexity.

**Comment by david-caro** [comment]
Mmm. Maybe it's not so hard to deactivate those facts I'm thinking of adding a fact to activate/deactivate the others (maybe through facter.d). They will be downloaded but not run except if you are on a master handled by the master module. What do you think?

**Pull request closed without merging**
