### PR TITLE
Automatic slave setup using swarm plugin

### PR DESCRIPTION
**Pull request by matthewbarr**
A fairly simple slave setup module.  Not heavily tested for all cases, but it does work as promised.  One area that needs help is the debian java package name, and also testing in using the default parameters, especially the slave_home directory.

### CODE REVIEW

**Comment by matthewbarr** [comment]
I've merged various upstream into this, which is likely why buildhive is not happy.  However, we finally found the reason that it was failing 50% of the time... setting cwd for puppet made all the difference.

**Comment by david-caro** [comment]
I like the simplicity.

pros:
- More simple, that's almost always good :)
- You can set up a node to autodiscover it's master

cons:
- You can't make sure that the slave is connected to the master you want, nor any master (just that the swarm jar is running on the client side)
- You have to specify on the master that you want the swarm plugin explicitly, not out-of-the-box solution
- and you must specify the same version for the master and for the node.
- You can't specify a node to be 'offline'
- No facts, that means that you can't use the facts elsewhere and it makes harder to know the state of the system
- As is, the slave needs connection to the internet to download the client
- Some configuration options are missing like labels and description (we use the labels a lot)

In this case, your solution does not solve my problems, so I prefer the solution that I wrote (that as far as I know does solve yours), I suppose that you prefer yours, so we need a kind third person (at least) to decide which one is the most suited for the job.

**Comment by rtyler** [comment]
@matthewbarr I suggest renaming the class `jenkins::slave::swarm`, then the module can support Swarm and other forms of slave configuration. I think that will also reduce the amount of class parameters it is required to take.

**Comment by rtyler** [comment]
Also, I can probably do this myself if you don't have time for the refactor, I just don't have a great environment to test the Swarm plugin right now.

**Comment by matthewbarr** [comment]
Not sure how the classes would be helped.. but OK w/ the rename.   I would want to make sure we're not forced to run the stored config code, since that's a performance hit.

**Comment by matthewbarr** [comment]
as for David's concerns:   
- If you specify the master you want to connect to, you won't connect to anything else.   You can't really verify that you're connected, but you can be sure you aren't connected to the wrong place.
- Version:  We can specify the version as a parameter w/ a default.  I tried to keep it minimal, but not hard to add that.
- Facts:  Maybe drop a fact for use w/ facter.d?
-  Internet:  That's an issue w/ the plugin code as well.  I've added the basic code to deal w/ a local repo for jenkins master, but haven't thought on how to deal w/ it otherwise.  We could easily add a parameter to locally store the jar, for enterprise shops.    
- Adding the labels & description.  They're both supported.  I just didn't implement in my quick version.  Had to fight with some issues of pathing, so got this stuff working first.  Fairly trivial add for the command line.

**Comment by matthewbarr** [comment]
I did try to evaluate if any of these parameters could be stored in a params.pp, but it didn't seem to make any sense.  Other than the version of the plugin, there's very little needed there.  

Maybe the best option would be to use class : jenkins::slave::master   in conjunction?  Or talk w/ the jenkins folks about maybe linking the swarm jar into the latest directory as well?   

Either way, may be worth talking w/ them about their ability to use mirrors.  They're not setup for a mirror / local repo at all at this time, so it might be worth working on upstream.

**Comment by rtyler** [comment]
@matthewbarr Heh, I'm the maintainer of the Jenkins mirror network and some other stuff, what is missing from our repos?

**Comment by david-caro** [comment]
Hey @matthewbarr:
- Master: The exec that you have declared will not get reloaded when the master changes, so once the process is running it stops knowing to which master it is connected and changing the master afterwards will not reload the process. Also, I always try to avoid pgrep -f sentences as they can end up doing very bad things (filtering by the name of the process is usually a very bad idea, for that you can use the services infrastructure, like system V) 
- Version: Please do, having to update two thing to change just one is very annoying.
- Facts: What you have with my manifests version is a list of facts on each master that describes which nodes are connected to that master and their statuses, i you want to export that to facts.d, you can do it, but its not trivial (not sure if it will end up being similar to mine).
- what about the offline statuses? And stopping the slave?

**Comment by matthewbarr** [comment]
@david-caro : 
1. pgrep was a quick & dirty solution for not running the slave again.  Not perfect.  Open to other ideas, but was a solution at the time.
2. We could switch to a init.d script.    I'd really prefer that the swarm plugin folks improve their plugin to use a config / password file as well, because i hate having the u/p on the command line in PS.
3. Master: Yep, it's not as robust if the master changes.  I've only got one master, and we could use a referesh if necessary, as a feature for the future.  If it was a config file, it'd be easy to use a notify.  I don't think w/ a class only & a variable that you can achieve a state to notify on change.
4. Facts: Yep, probably not in the spec of the quick & easy.      Might be able to adapt your code to be useful, but probably not worth it.  I'd expect most people to use the jenkins dashboard to temporarily disable a node...  and the init scripts would handle stopping the node if necessary.

I think we're hitting the key details here- basically, these 2 modules do similar things, but very differently.  There are differences.  The way i did mine was very easy on the coding, and very quick to setup, and can be up & running w/o any storeconfigs.  Since that requires puppetDB these days, it's a additional requirement.

This may be a case of we agree to have both in the world.  There are places that my code can be upgraded, and improved.    The biggest upside for me is that it's very understandable, and very easy to use.

For many people, swarm code will work.  It's easy.  For those that need more, your code is there.  It may even be time to separate the code sets.  I wouldn't want to load the type & facter code..

**Comment by matthewbarr** [comment]
@rtyler Jenkins Wise:
1. a way to specify the latest version of a LTS plugin, programmatically.  Maybe there's an api, which would replace the jenkins::plugin code overall.  That might solve the hpi & jpi  issues.
1. Didn't seem like there was an obvious way to use a local mirror / repo for jenkins to check for plugins and such.  

3- this might not really be a "mirror" issue vs moving to a system that's more enterprise savy and use something akin to a yum repo for it's plugins.
1. a way to link the swarm plugin latest version into a  URL like LATEST.
   http://maven.jenkins-ci.org/content/repositories/releases/org/jenkins-ci/plugins/swarm-client/  

Not sure which part of the jenkins team would handle that, but it'd would moot the issue w/ specifying a version of the plugin.

(we'd still maybe move to a central version number, but default wouldn't need to be set, which would be better..)

**Comment by matthewbarr** [comment]
BTW- the issue w/ cloudbees is a bad file in the script to setup ruby.  Looks like a job definition issue in Jenkins :)

**Comment by matthewbarr** [comment]
@rtyler :   Actually, reveiwing the concept of renaming, I'm not sure what it will help.  The paramaters aren't going to help, since they're mostly set from outside the system.  They have sane defaults.  

Also, you can easily test swarm, by just telling it the master URL.

2nd: the biggest issue I have with merging in david's slave code is not his slave module itself, but the code that runs on the master & the facts.  I'll ask after a way to package it so that it's not on by default, if possible.  It would break in my environment, and I'm not sure what running it would do if you don't have a DB to store configs in.

**Comment by david-caro** [comment]
@matthewbarr: I agree with rtyler about the renaming, it suits better because you need to provide the slaves through a plugin, so it's not the 'default' way of setting up slaves.

About the merge, yes, if you are not using storeconfigs the master code will fail. Maybe use a parameter to deactivate those features? I can even change the slaves class to be slaves::storeconfigs to make clear that it uses the storeconfigs.
Btw. why don't you use storeconfigs? (just curious)

**Comment by matthewbarr** [comment]
@david-caro 
1. Added a init script.  Much better.   If you change the master, it'll restart.  If you change any parameters, it'll restart. Pid files  & lock files oh my!
2. Store configs : Slow, require a DB.  Don't have any real need for them yet,  and they don't work on masterless systems.
3. Custom facts & functions: Can't be turned off.  You run them in your master & on your hosts. I prefer a class that only does something when explicitly called.  

@rtyler This was probably my last big change.  If we need to move the code someplace, we can, but other than that, it's working pretty nicely right now.

I think it even works w/ heira if you've got it installed, in 3.0 & above.

**Comment by rtyler** [comment]
I'm going to merge this now, and start tinkering.

**Comment by matthewbarr** [comment]
let me know if there's any issues.  I found and fixed a few major issues w/ the default, no parameters.  a lack of UID  would break the init script.

I do think it needs a debian/ ubuntu specific package name.  (for Java.)

**Pull request merged**
