### PR TITLE
Resolve 'invalid tag' error on puppet 2.7.20 with puppetlabs-firewall module installed.

### PR DESCRIPTION
**Pull request by morganfletcher**
...e the 'error Invalid tag "::firewall"' on puppet 2.7.20 with the puppetlabs-firewall module installed, and still successfully ensures the firewall rule in iptables.

### CODE REVIEW

**Comment by morganfletcher** [comment]
The buildhive failure doesn't seem related to my change...

**Comment by tastybug** [comment]
Confirmed, got the same problem.

**Comment by feniix** [comment]
Same happens on puppet 3.1.1 this patch fixes the issue.

**Comment by rtyler** [comment]
I merged another pull request that covered this, just happened to see it first.

**Pull request closed without merging**
