### PR TITLE
Avoid duplicate File['/etc/apt/sources.list.d'] by checking whether it's...

### PR DESCRIPTION
**Pull request by tbroyer**
... already defined.

Other modules define a File['/etc/apt/sources.list.d'](e.g. https://github.com/puppetlabs/puppet-apt/blob/master/manifests/init.pp#L56), so they will conflict with puppet-jenkins.

### CODE REVIEW

**Comment by tbroyer** [comment]
Note that this change is not enough for puppet-jenkins to work with puppet-apt, as puppet-apt does not declare File['/etc/apt/sources.list.d'] but File['sources.list'] with a path=>'/etc/apt/sources.list.d', so it fails with the following error:

```
Cannot alias File[sources.list.d] to ["/etc/apt/sources.list.d"] at /tmp/vagrant-puppet/modules-0/apt/manifests/init.pp:63; resource ["File", "/etc/apt/sources.list.d"] already defined at /tmp/vagrant-puppet/modules-0/jenkins/manifests/repo/debian.pp:6
```

I'll make a pull request on puppet-apt for that (and maybe I'll make a follow-up pull request here to move to using puppet-apt)

**Comment by tbroyer** [comment]
See https://github.com/puppetlabs/puppet-apt/pull/28

With these two changes, puppet-apt and puppet-jenkins no longer conflict.

**Comment by reidmv** [comment]
See further discussion on [puppetlabs/puppetlabs-apt/pull/28](https://github.com/puppetlabs/puppet-apt/pull/28). I've submitted an alternative pull request [rtyler/puppet-jenkins/pull/8](https://github.com/rtyler/puppet-jenkins/pull/8) as an implementation of the suggestion made by tbroyer, "follow-up pull request here to move to using puppet-apt".

**Comment by rtyler** [comment]
This can be closed now that #8 was merged I believe

**Pull request closed without merging**
